"""Tier C2 + C3 + C4: per-sector, per-cohort, and per-fold aggregate
analyses for InVAR-SWA test predictions.

For each fold (1, 2):
  - C2: per-sector_id daily rank IC (across active stocks in that sector)
  - C3: per-size_decile daily rank IC, per-age_bucket daily rank IC
  - C4: long-short Sharpe / NDCG@10 / NDCG@50 aggregated across seeds

Outputs a single Markdown table to docs/invar_swa_breakdown.md.
"""
from __future__ import annotations

from pathlib import Path
import json

import numpy as np
import pandas as pd
import scipy.stats as st


SEEDS = [42, 43, 44, 45, 46]
FOLDS = [1, 2]


def load_predictions(fold: int) -> pd.DataFrame | None:
    """Load and concat all 5-seed test predictions for one fold."""
    rows = []
    for s in SEEDS:
        path = Path(
            f"experiments/invar/swa/fold{fold}/seed{s}_designR/predictions.parquet"
        )
        if not path.exists():
            return None
        df = pd.read_parquet(path)
        df["seed"] = s
        rows.append(df)
    return pd.concat(rows, ignore_index=True)


def per_day_rank_ic(df: pd.DataFrame) -> pd.Series:
    """Per-(date) Spearman rho between y_hat and y_true on active rows."""
    out = []
    for date, sub in df.groupby("date"):
        sub = sub[sub["y_true"] != 0]
        if len(sub) < 5:
            continue
        rho, _ = st.spearmanr(sub["y_hat"], sub["y_true"])
        out.append({"date": date, "rho": float(rho)})
    return pd.DataFrame(out).set_index("date")["rho"]


def main() -> None:
    out_lines = ["# InVAR-SWA breakdown (Tier C2 + C3 + C4)\n",
                  "Per-sector / per-cohort / aggregate analysis on the 5-seed ",
                  "InVAR-SWA test predictions. Auto-generated by ",
                  "`scripts/invar_swa_per_sector_cohort.py`.\n\n"]

    # SECTOR_ID is 0..11 in our LATTICE cohort encoding; size_decile 0..9; age_bucket 0..N.
    # Keep names simple - we don't have a sector dictionary in this script.
    for fold in FOLDS:
        df = load_predictions(fold)
        if df is None:
            print(f"Fold {fold}: missing predictions, skip")
            continue
        out_lines.append(f"\n## Fold {fold}\n\n")

        # --- C2: Per-sector daily rank IC (averaged across seeds) ---
        out_lines.append("### Per-sector daily rank IC (averaged across 5 seeds)\n\n")
        out_lines.append("| sector_id | mean rank IC | std | n_days | n_active_avg |\n")
        out_lines.append("|-----------|-------------:|----:|-------:|-------------:|\n")
        sec_rows = []
        for sec_id, sec_df in df.groupby("sector_id"):
            ric = per_day_rank_ic(sec_df)
            n_active_avg = (
                sec_df.groupby("date").size().mean() / len(SEEDS)
            )
            if len(ric) == 0:
                continue
            sec_rows.append({
                "sector_id": int(sec_id),
                "mean_rank_ic": float(ric.mean()),
                "std": float(ric.std()),
                "n_days": int(len(ric)),
                "n_active_avg": float(n_active_avg),
            })
        sec_rows.sort(key=lambda r: r["mean_rank_ic"], reverse=True)
        for r in sec_rows:
            out_lines.append(
                f"| {r['sector_id']} | {r['mean_rank_ic']:+.4f} | "
                f"{r['std']:.4f} | {r['n_days']} | {r['n_active_avg']:.1f} |\n"
            )

        # --- C3: Per-size-decile daily rank IC ---
        out_lines.append("\n### Per-size-decile daily rank IC\n\n")
        out_lines.append("| size_decile | mean rank IC | std | n_days |\n")
        out_lines.append("|-------------|-------------:|----:|-------:|\n")
        sd_rows = []
        for sd_id, sd_df in df.groupby("size_decile"):
            ric = per_day_rank_ic(sd_df)
            if len(ric) == 0:
                continue
            sd_rows.append({
                "size_decile": int(sd_id),
                "mean_rank_ic": float(ric.mean()),
                "std": float(ric.std()),
                "n_days": int(len(ric)),
            })
        sd_rows.sort(key=lambda r: r["size_decile"])
        for r in sd_rows:
            out_lines.append(
                f"| {r['size_decile']} | {r['mean_rank_ic']:+.4f} | "
                f"{r['std']:.4f} | {r['n_days']} |\n"
            )

        # --- C3b: Per-age-bucket daily rank IC ---
        out_lines.append("\n### Per-age-bucket daily rank IC\n\n")
        out_lines.append("| age_bucket | mean rank IC | std | n_days |\n")
        out_lines.append("|-----------|-------------:|----:|-------:|\n")
        ab_rows = []
        for ab_id, ab_df in df.groupby("age_bucket"):
            ric = per_day_rank_ic(ab_df)
            if len(ric) == 0:
                continue
            ab_rows.append({
                "age_bucket": int(ab_id),
                "mean_rank_ic": float(ric.mean()),
                "std": float(ric.std()),
                "n_days": int(len(ric)),
            })
        ab_rows.sort(key=lambda r: r["age_bucket"])
        for r in ab_rows:
            out_lines.append(
                f"| {r['age_bucket']} | {r['mean_rank_ic']:+.4f} | "
                f"{r['std']:.4f} | {r['n_days']} |\n"
            )

        # --- C4: Aggregate metrics from each seed's results.json ---
        out_lines.append("\n### Per-seed aggregate metrics\n\n")
        out_lines.append("| seed | rank IC | NDCG@10 | NDCG@50 | LS Sharpe |\n")
        out_lines.append("|------|--------:|--------:|--------:|---------:|\n")
        for s in SEEDS:
            rj = Path(
                f"experiments/invar/swa/fold{fold}/seed{s}_designR/results.json"
            )
            if not rj.exists():
                continue
            with open(rj) as f:
                d = json.load(f)
            out_lines.append(
                f"| {s} | {d.get('test_rank_ic'):+.4f} | "
                f"{d.get('test_ndcg10', float('nan')):.4f} | "
                f"{d.get('test_ndcg50', float('nan')):.4f} | "
                f"{d.get('test_sharpe', float('nan')):.3f} |\n"
            )

    out_path = Path("docs/invar_swa_breakdown.md")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w") as f:
        f.writelines(out_lines)
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
