"""Smoke-test the public StockTwits S3 corpus.

Fetches only the first few MB of each category's first file via HTTP
Range requests against the public S3 HTTPS endpoint, and reports schema
and sample rows. Avoids downloading whole files (each is 50 to 225 MB).

Uses plain `requests` with a `Range: bytes=0-N` header. s3fs with anon=True
was observed to hang on this corpus (likely pulling whole files despite
the read(n) limit); direct Range is deterministic and fast.

Usage:
    python3 scripts/stocktwits_smoke_test.py
"""
from __future__ import annotations

import io
import sys
from pathlib import Path

import pandas as pd
import requests


BASE = "stocktwits-nyu/dataset/v1/data/csv"
SAMPLES = {
    "symbols": f"{BASE}/symbols/symbol_000.csv",
    "feature_wo_messages": f"{BASE}/feature_wo_messages/feature_wo_messages_000.csv",
    "msg_info": f"{BASE}/msg_info/msg_info_00.csv",
    "sentiments": f"{BASE}/sentiments/sentiment_00.csv",
}

READ_BYTES = 2 * 1024 * 1024   # 2 MB per file; plenty of rows for schema


def sample_head(s3_path: str, n_bytes: int = READ_BYTES) -> pd.DataFrame:
    bucket_and_key = s3_path.split("/", 1)
    bucket = bucket_and_key[0]
    key = bucket_and_key[1]
    url = f"https://{bucket}.s3.amazonaws.com/{key}"
    headers = {"Range": f"bytes=0-{n_bytes - 1}"}
    r = requests.get(url, headers=headers, timeout=30)
    r.raise_for_status()
    raw = r.content
    last_newline = raw.rfind(b"\n")
    if last_newline > 0:
        raw = raw[:last_newline]
    return pd.read_csv(io.BytesIO(raw))


def main() -> None:
    lines: list[str] = []

    def out(s: str = "") -> None:
        print(s, flush=True)
        lines.append(s)

    for cat, path in SAMPLES.items():
        out(f"=== {cat} ===")
        out(f"s3://{path}")
        try:
            df = sample_head(path)
        except Exception as e:
            out(f"  ERROR: {type(e).__name__}: {e}")
            out("")
            continue
        out(f"rows in 2MB sample: {len(df)}")
        out(f"columns: {list(df.columns)}")
        out("dtypes:")
        for col, dt in df.dtypes.items():
            out(f"  {col}: {dt}")
        out("first 3 rows:")
        out(df.head(3).to_string(max_cols=20, max_colwidth=60))
        if "created_at" in df.columns:
            out(f"created_at range: {df['created_at'].min()}  to  {df['created_at'].max()}")
        if "symbol_list" in df.columns:
            out("symbol_list samples:")
            for s in df["symbol_list"].dropna().head(5):
                out(f"  {s!r}")
        out("")

    Path("docs/stocktwits_smoke_test.md").parent.mkdir(parents=True, exist_ok=True)
    Path("docs/stocktwits_smoke_test.md").write_text(
        "# StockTwits S3 smoke test\n\nGenerated by `scripts/stocktwits_smoke_test.py`.\n\n```\n"
        + "\n".join(lines)
        + "\n```\n"
    )


if __name__ == "__main__":
    main()
